fix: avoid crash from missing function check in `require-super-in-init` rule
Fixes the following error caused by the included test case.

```
TypeError: Cannot read property 'body' of undefined
```