fix: handle empty return statement in `require-computed-macros` rule
```
  ● require-computed-macros › valid › computed(function() { return; })

    TypeError: Cannot read property 'type' of null
    Occurred while linting <input>:1

      273 |  */
      274 | function isUnaryExpression(node) {
    > 275 |   return node !== undefined && node.type === 'UnaryExpression';
          |                                     ^
      276 | }
      277 |
      278 | /**

      at Object.type [as isUnaryExpression] (lib/utils/types.js:275:37)
      at CallExpression (lib/rules/require-computed-macros.js:175:19)
```