fix: avoid crash when missing arguments to `this.route()` in `route-path-style` rule
Handle this test case:

```
this.route();
```

Which causes this error:

```
TypeError: Cannot read property 'value' of undefined
```